/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as TcoRouteImport } from './routes/tco'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ModeratorRouteImport } from './routes/moderator'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as ModeratorIndexRouteImport } from './routes/moderator.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorTeamRouteImport } from './routes/vendor.team'
import { Route as VendorInboxRouteImport } from './routes/vendor.inbox'
import { Route as SystemsSlugRouteImport } from './routes/systems.$slug'
import { Route as ModeratorScraperRouteImport } from './routes/moderator/scraper'
import { Route as ModeratorCleaningQueueRouteImport } from './routes/moderator/cleaning-queue'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AdminWebsiteScraperRouteImport } from './routes/admin.website-scraper'
import { Route as AdminScraperRouteImport } from './routes/admin.scraper'
import { Route as AdminModeratorsRouteImport } from './routes/admin.moderators'
import { Route as AdminCleaningQueueRouteImport } from './routes/admin.cleaning-queue'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as VendorSystemsIndexRouteImport } from './routes/vendor.systems.index'
import { Route as VendorCompanyIndexRouteImport } from './routes/vendor/company/index'
import { Route as VendorSystemsIdRouteImport } from './routes/vendor.systems.$id'
import { Route as ModeratorItemIdRouteImport } from './routes/moderator.item.$id'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const TcoRoute = TcoRouteImport.update({
  id: '/tco',
  path: '/tco',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorRoute = ModeratorRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const ModeratorIndexRoute = ModeratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeratorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorTeamRoute = VendorTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => VendorRoute,
} as any)
const VendorInboxRoute = VendorInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => VendorRoute,
} as any)
const SystemsSlugRoute = SystemsSlugRouteImport.update({
  id: '/systems/$slug',
  path: '/systems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorScraperRoute = ModeratorScraperRouteImport.update({
  id: '/scraper',
  path: '/scraper',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorCleaningQueueRoute = ModeratorCleaningQueueRouteImport.update({
  id: '/cleaning-queue',
  path: '/cleaning-queue',
  getParentRoute: () => ModeratorRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AdminWebsiteScraperRoute = AdminWebsiteScraperRouteImport.update({
  id: '/website-scraper',
  path: '/website-scraper',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScraperRoute = AdminScraperRouteImport.update({
  id: '/scraper',
  path: '/scraper',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModeratorsRoute = AdminModeratorsRouteImport.update({
  id: '/moderators',
  path: '/moderators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCleaningQueueRoute = AdminCleaningQueueRouteImport.update({
  id: '/cleaning-queue',
  path: '/cleaning-queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const VendorSystemsIndexRoute = VendorSystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorCompanyIndexRoute = VendorCompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSystemsIdRoute = VendorSystemsIdRouteImport.update({
  id: '/systems/$id',
  path: '/systems/$id',
  getParentRoute: () => VendorRoute,
} as any)
const ModeratorItemIdRoute = ModeratorItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => ModeratorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRouteWithChildren
  '/chats': typeof ChatsRoute
  '/compare': typeof CompareRoute
  '/moderator': typeof ModeratorRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tco': typeof TcoRoute
  '/vendor': typeof VendorRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cleaning-queue': typeof AdminCleaningQueueRoute
  '/admin/moderators': typeof AdminModeratorsRoute
  '/admin/scraper': typeof AdminScraperRoute
  '/admin/website-scraper': typeof AdminWebsiteScraperRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/moderator/cleaning-queue': typeof ModeratorCleaningQueueRoute
  '/moderator/scraper': typeof ModeratorScraperRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/vendor/inbox': typeof VendorInboxRoute
  '/vendor/team': typeof VendorTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/moderator/': typeof ModeratorIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/moderator/item/$id': typeof ModeratorItemIdRoute
  '/vendor/systems/$id': typeof VendorSystemsIdRoute
  '/vendor/company/': typeof VendorCompanyIndexRoute
  '/vendor/systems/': typeof VendorSystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRouteWithChildren
  '/chats': typeof ChatsRoute
  '/compare': typeof CompareRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tco': typeof TcoRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cleaning-queue': typeof AdminCleaningQueueRoute
  '/admin/moderators': typeof AdminModeratorsRoute
  '/admin/scraper': typeof AdminScraperRoute
  '/admin/website-scraper': typeof AdminWebsiteScraperRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/moderator/cleaning-queue': typeof ModeratorCleaningQueueRoute
  '/moderator/scraper': typeof ModeratorScraperRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/vendor/inbox': typeof VendorInboxRoute
  '/vendor/team': typeof VendorTeamRoute
  '/admin': typeof AdminIndexRoute
  '/moderator': typeof ModeratorIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/moderator/item/$id': typeof ModeratorItemIdRoute
  '/vendor/systems/$id': typeof VendorSystemsIdRoute
  '/vendor/company': typeof VendorCompanyIndexRoute
  '/vendor/systems': typeof VendorSystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRouteWithChildren
  '/chats': typeof ChatsRoute
  '/compare': typeof CompareRoute
  '/moderator': typeof ModeratorRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tco': typeof TcoRoute
  '/vendor': typeof VendorRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cleaning-queue': typeof AdminCleaningQueueRoute
  '/admin/moderators': typeof AdminModeratorsRoute
  '/admin/scraper': typeof AdminScraperRoute
  '/admin/website-scraper': typeof AdminWebsiteScraperRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/moderator/cleaning-queue': typeof ModeratorCleaningQueueRoute
  '/moderator/scraper': typeof ModeratorScraperRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/vendor/inbox': typeof VendorInboxRoute
  '/vendor/team': typeof VendorTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/moderator/': typeof ModeratorIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/moderator/item/$id': typeof ModeratorItemIdRoute
  '/vendor/systems/$id': typeof VendorSystemsIdRoute
  '/vendor/company/': typeof VendorCompanyIndexRoute
  '/vendor/systems/': typeof VendorSystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assessment'
    | '/auth'
    | '/chats'
    | '/compare'
    | '/moderator'
    | '/profile'
    | '/settings'
    | '/tco'
    | '/vendor'
    | '/watchlist'
    | '/admin/audit'
    | '/admin/cleaning-queue'
    | '/admin/moderators'
    | '/admin/scraper'
    | '/admin/website-scraper'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/moderator/cleaning-queue'
    | '/moderator/scraper'
    | '/systems/$slug'
    | '/vendor/inbox'
    | '/vendor/team'
    | '/admin/'
    | '/moderator/'
    | '/vendor/'
    | '/moderator/item/$id'
    | '/vendor/systems/$id'
    | '/vendor/company/'
    | '/vendor/systems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/auth'
    | '/chats'
    | '/compare'
    | '/profile'
    | '/settings'
    | '/tco'
    | '/watchlist'
    | '/admin/audit'
    | '/admin/cleaning-queue'
    | '/admin/moderators'
    | '/admin/scraper'
    | '/admin/website-scraper'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/moderator/cleaning-queue'
    | '/moderator/scraper'
    | '/systems/$slug'
    | '/vendor/inbox'
    | '/vendor/team'
    | '/admin'
    | '/moderator'
    | '/vendor'
    | '/moderator/item/$id'
    | '/vendor/systems/$id'
    | '/vendor/company'
    | '/vendor/systems'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assessment'
    | '/auth'
    | '/chats'
    | '/compare'
    | '/moderator'
    | '/profile'
    | '/settings'
    | '/tco'
    | '/vendor'
    | '/watchlist'
    | '/admin/audit'
    | '/admin/cleaning-queue'
    | '/admin/moderators'
    | '/admin/scraper'
    | '/admin/website-scraper'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/moderator/cleaning-queue'
    | '/moderator/scraper'
    | '/systems/$slug'
    | '/vendor/inbox'
    | '/vendor/team'
    | '/admin/'
    | '/moderator/'
    | '/vendor/'
    | '/moderator/item/$id'
    | '/vendor/systems/$id'
    | '/vendor/company/'
    | '/vendor/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChatsRoute: typeof ChatsRoute
  CompareRoute: typeof CompareRoute
  ModeratorRoute: typeof ModeratorRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TcoRoute: typeof TcoRoute
  VendorRoute: typeof VendorRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  SystemsSlugRoute: typeof SystemsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tco': {
      id: '/tco'
      path: '/tco'
      fullPath: '/tco'
      preLoaderRoute: typeof TcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator': {
      id: '/moderator'
      path: '/moderator'
      fullPath: '/moderator'
      preLoaderRoute: typeof ModeratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/moderator/': {
      id: '/moderator/'
      path: '/'
      fullPath: '/moderator/'
      preLoaderRoute: typeof ModeratorIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/team': {
      id: '/vendor/team'
      path: '/team'
      fullPath: '/vendor/team'
      preLoaderRoute: typeof VendorTeamRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/inbox': {
      id: '/vendor/inbox'
      path: '/inbox'
      fullPath: '/vendor/inbox'
      preLoaderRoute: typeof VendorInboxRouteImport
      parentRoute: typeof VendorRoute
    }
    '/systems/$slug': {
      id: '/systems/$slug'
      path: '/systems/$slug'
      fullPath: '/systems/$slug'
      preLoaderRoute: typeof SystemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/scraper': {
      id: '/moderator/scraper'
      path: '/scraper'
      fullPath: '/moderator/scraper'
      preLoaderRoute: typeof ModeratorScraperRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/moderator/cleaning-queue': {
      id: '/moderator/cleaning-queue'
      path: '/cleaning-queue'
      fullPath: '/moderator/cleaning-queue'
      preLoaderRoute: typeof ModeratorCleaningQueueRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/website-scraper': {
      id: '/admin/website-scraper'
      path: '/website-scraper'
      fullPath: '/admin/website-scraper'
      preLoaderRoute: typeof AdminWebsiteScraperRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scraper': {
      id: '/admin/scraper'
      path: '/scraper'
      fullPath: '/admin/scraper'
      preLoaderRoute: typeof AdminScraperRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderators': {
      id: '/admin/moderators'
      path: '/moderators'
      fullPath: '/admin/moderators'
      preLoaderRoute: typeof AdminModeratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cleaning-queue': {
      id: '/admin/cleaning-queue'
      path: '/cleaning-queue'
      fullPath: '/admin/cleaning-queue'
      preLoaderRoute: typeof AdminCleaningQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/systems/': {
      id: '/vendor/systems/'
      path: '/systems'
      fullPath: '/vendor/systems/'
      preLoaderRoute: typeof VendorSystemsIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/company/': {
      id: '/vendor/company/'
      path: '/company'
      fullPath: '/vendor/company/'
      preLoaderRoute: typeof VendorCompanyIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/systems/$id': {
      id: '/vendor/systems/$id'
      path: '/systems/$id'
      fullPath: '/vendor/systems/$id'
      preLoaderRoute: typeof VendorSystemsIdRouteImport
      parentRoute: typeof VendorRoute
    }
    '/moderator/item/$id': {
      id: '/moderator/item/$id'
      path: '/item/$id'
      fullPath: '/moderator/item/$id'
      preLoaderRoute: typeof ModeratorItemIdRouteImport
      parentRoute: typeof ModeratorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCleaningQueueRoute: typeof AdminCleaningQueueRoute
  AdminModeratorsRoute: typeof AdminModeratorsRoute
  AdminScraperRoute: typeof AdminScraperRoute
  AdminWebsiteScraperRoute: typeof AdminWebsiteScraperRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCleaningQueueRoute: AdminCleaningQueueRoute,
  AdminModeratorsRoute: AdminModeratorsRoute,
  AdminScraperRoute: AdminScraperRoute,
  AdminWebsiteScraperRoute: AdminWebsiteScraperRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ModeratorRouteChildren {
  ModeratorCleaningQueueRoute: typeof ModeratorCleaningQueueRoute
  ModeratorScraperRoute: typeof ModeratorScraperRoute
  ModeratorIndexRoute: typeof ModeratorIndexRoute
  ModeratorItemIdRoute: typeof ModeratorItemIdRoute
}

const ModeratorRouteChildren: ModeratorRouteChildren = {
  ModeratorCleaningQueueRoute: ModeratorCleaningQueueRoute,
  ModeratorScraperRoute: ModeratorScraperRoute,
  ModeratorIndexRoute: ModeratorIndexRoute,
  ModeratorItemIdRoute: ModeratorItemIdRoute,
}

const ModeratorRouteWithChildren = ModeratorRoute._addFileChildren(
  ModeratorRouteChildren,
)

interface VendorRouteChildren {
  VendorInboxRoute: typeof VendorInboxRoute
  VendorTeamRoute: typeof VendorTeamRoute
  VendorIndexRoute: typeof VendorIndexRoute
  VendorSystemsIdRoute: typeof VendorSystemsIdRoute
  VendorCompanyIndexRoute: typeof VendorCompanyIndexRoute
  VendorSystemsIndexRoute: typeof VendorSystemsIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorInboxRoute: VendorInboxRoute,
  VendorTeamRoute: VendorTeamRoute,
  VendorIndexRoute: VendorIndexRoute,
  VendorSystemsIdRoute: VendorSystemsIdRoute,
  VendorCompanyIndexRoute: VendorCompanyIndexRoute,
  VendorSystemsIndexRoute: VendorSystemsIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRouteWithChildren,
  ChatsRoute: ChatsRoute,
  CompareRoute: CompareRoute,
  ModeratorRoute: ModeratorRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TcoRoute: TcoRoute,
  VendorRoute: VendorRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  SystemsSlugRoute: SystemsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
